// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQeocQSWGWHO2KNvAzPEaX0a5Mnsjf0xk',
    appId: '1:703974751093:web:25f88f74d9b90a52ecf13c',
    messagingSenderId: '703974751093',
    projectId: 'smarthomeiot-f8436',
    authDomain: 'smarthomeiot-f8436.firebaseapp.com',
    databaseURL: 'https://smarthomeiot-f8436-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomeiot-f8436.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8ikKwqeCrQ7-kQSiUWvoFrCeew52VEqM',
    appId: '1:703974751093:android:b9f98d5a21694d36ecf13c',
    messagingSenderId: '703974751093',
    projectId: 'smarthomeiot-f8436',
    databaseURL: 'https://smarthomeiot-f8436-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomeiot-f8436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUtdBMPWRv55Q_iqMGCiDLbbPmMJM0-jc',
    appId: '1:703974751093:ios:3a1be093738b80e1ecf13c',
    messagingSenderId: '703974751093',
    projectId: 'smarthomeiot-f8436',
    databaseURL: 'https://smarthomeiot-f8436-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomeiot-f8436.firebasestorage.app',
    iosClientId: '703974751093-kummjj528hg7mmekduhotp76f6rl6oem.apps.googleusercontent.com',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUtdBMPWRv55Q_iqMGCiDLbbPmMJM0-jc',
    appId: '1:703974751093:ios:3a1be093738b80e1ecf13c',
    messagingSenderId: '703974751093',
    projectId: 'smarthomeiot-f8436',
    databaseURL: 'https://smarthomeiot-f8436-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomeiot-f8436.firebasestorage.app',
    iosClientId: '703974751093-kummjj528hg7mmekduhotp76f6rl6oem.apps.googleusercontent.com',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQeocQSWGWHO2KNvAzPEaX0a5Mnsjf0xk',
    appId: '1:703974751093:web:de538c561ef9e266ecf13c',
    messagingSenderId: '703974751093',
    projectId: 'smarthomeiot-f8436',
    authDomain: 'smarthomeiot-f8436.firebaseapp.com',
    databaseURL: 'https://smarthomeiot-f8436-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomeiot-f8436.firebasestorage.app',
  );
}
